//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markdown
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int ID { get; set; }
        public string Name_Material { get; set; }
        public int Type_material { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public int QuantityInStock { get; set; }
        public int MinimumQuantity { get; set; }
        public int QuantityInThePackage { get; set; }
        public int UnitOfMeasurement { get; set; }
    
        public virtual TypeMaterials TypeMaterials { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement1 { get; set; }
    }
}
